{
 "title": "BTC in Time",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Anomalies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "SELECT symbol, price, ingestion_ts\nFROM stocks\nWHERE symbol = 'BINANCE:BTCUSDT' \n  AND ingestion_ts >= $__timeFrom \n  AND ingestion_ts <= $__timeTo ALLOW FILTERING;"
    },
    {
     "target": "SELECT symbol, price, ingestion_ts from anomalies WHERE symbol = 'BINANCE:BTCUSDT' \n  AND ingestion_ts >= $__timeFrom \n  AND ingestion_ts <= $__timeTo ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Volume Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "SELECT symbol, volume, ingestion_ts\nFROM stocks\nWHERE symbol = 'BINANCE:BTCUSDT' \n  AND ingestion_ts >= $__timeFrom \n  AND ingestion_ts <= $__timeTo ALLOW FILTERING;"
    },
    {
     "target": "SELECT symbol, volume, ingestion_ts from anomalies WHERE symbol = 'BINANCE:BTCUSDT' \n  AND ingestion_ts >= $__timeFrom \n  AND ingestion_ts <= $__timeTo ALLOW FILTERING;"
    }
   ]
  },
  { "title": "BTC in Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "price",
     "target": "select symbol, price, trade_ts from stocks where symbol = 'BINANCE:BTCUSDT' and trade_ts>$__timeFrom and trade_ts<$__timeTo;"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "volume",
     "target": "select symbol, volume, trade_ts from stocks where symbol = 'BINANCE:BTCUSDT' and trade_ts>$__timeFrom and trade_ts<$__timeTo;"
    }
   ]
  }
 ]
}